name: Keep Active

on:
  schedule:
    - cron: '0 0 * * 0,3' # Runs at 00:00 UTC on Sundays and Wednesdays
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Keep Active Function
        run: |
          curl -X POST \
            "${{ secrets.SUPABASE_URL }}/rest/v1/rpc/keep_active" \
            -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}' \
            --fail
          echo "Keep Active request sent successfully."
