name: Keep Active

on:
  schedule:
    - cron: '0 0 * * 0,3' # Runs at 00:00 UTC on Sundays and Wednesdays
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: "3.27.4"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Run Dart script with environment variables
        run: dart run lib/scripts/keep_active.dart
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
